<html>
  <head>
    <?php $this->headTitle('Trumpet') ?>

    <?php $this->headMeta()->append(array('http-equiv' => 'Content-Type', 'content' => 'text/html; charset=iso-8859-1')) ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>

  </head>
  <body>
    <?php echo $this->content ?>
  </body>
</html>