#!/bin/sh

case $1 in
	start)
		exit 0
	;;
	stop)
		exit 0
	;;
	status)
		exit 0
	;;
	log)
		echo "Trumpet is installed properly. To access it, click icon under 'admin' menu">/tmp/cc.log
		echo "/tmp/cc.log";
		exit 0
	;;
esac
                                     
